/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "gate_service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(gate_v1_BoundingBox, gate_v1_BoundingBox, AUTO)


PB_BIND(gate_v1_Point3D, gate_v1_Point3D, AUTO)


PB_BIND(gate_v1_BoundingBox3D, gate_v1_BoundingBox3D, AUTO)


PB_BIND(gate_v1_PlateDetection, gate_v1_PlateDetection, AUTO)


PB_BIND(gate_v1_VehicleDetection, gate_v1_VehicleDetection, AUTO)


PB_BIND(gate_v1_DetectionFrame, gate_v1_DetectionFrame, AUTO)


PB_BIND(gate_v1_AuthorizeRequest, gate_v1_AuthorizeRequest, AUTO)


PB_BIND(gate_v1_AuthDecision, gate_v1_AuthDecision, AUTO)


PB_BIND(gate_v1_Telemetry, gate_v1_Telemetry, AUTO)


PB_BIND(gate_v1_GateCommand, gate_v1_GateCommand, AUTO)


PB_BIND(gate_v1_CommandAck, gate_v1_CommandAck, AUTO)


PB_BIND(gate_v1_FaultEvent, gate_v1_FaultEvent, 2)


PB_BIND(gate_v1_FaultEvent_ContextEntry, gate_v1_FaultEvent_ContextEntry, AUTO)


PB_BIND(gate_v1_OtaManifest, gate_v1_OtaManifest, 2)


PB_BIND(gate_v1_OtaChunk, gate_v1_OtaChunk, 4)


PB_BIND(gate_v1_OtaProgress, gate_v1_OtaProgress, AUTO)


PB_BIND(gate_v1_DashboardEvent, gate_v1_DashboardEvent, 2)


PB_BIND(gate_v1_DashboardSubscription, gate_v1_DashboardSubscription, AUTO)


PB_BIND(gate_v1_TimeWindow, gate_v1_TimeWindow, AUTO)


PB_BIND(gate_v1_Allowlistentry, gate_v1_Allowlistentry, AUTO)


PB_BIND(gate_v1_UpsertAllowlistRequest, gate_v1_UpsertAllowlistRequest, AUTO)


PB_BIND(gate_v1_UpsertAllowlistResponse, gate_v1_UpsertAllowlistResponse, AUTO)


PB_BIND(gate_v1_ListAllowlistRequest, gate_v1_ListAllowlistRequest, AUTO)


PB_BIND(gate_v1_ListAllowlistResponse, gate_v1_ListAllowlistResponse, AUTO)


PB_BIND(gate_v1_DeleteAllowlistRequest, gate_v1_DeleteAllowlistRequest, AUTO)


PB_BIND(gate_v1_ControlEnvelope, gate_v1_ControlEnvelope, 2)



















