/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_GATE_V1_GATE_SERVICE_PB_H_INCLUDED
#define PB_GATE_V1_GATE_SERVICE_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/timestamp.pb.h"
#include "google/protobuf/duration.pb.h"
#include "google/protobuf/empty.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* VehicleClass — produced by the LiDAR pipeline. Matches the 8-class taxonomy
 from docs/diagrams/03-lidar-subsystem.mmd. Order is stable. */
typedef enum _gate_v1_VehicleClass {
    gate_v1_VehicleClass_VEHICLE_CLASS_UNKNOWN = 0,
    gate_v1_VehicleClass_VEHICLE_CLASS_PEDESTRIAN = 1,
    gate_v1_VehicleClass_VEHICLE_CLASS_BICYCLE = 2,
    gate_v1_VehicleClass_VEHICLE_CLASS_MOTORCYCLE = 3,
    gate_v1_VehicleClass_VEHICLE_CLASS_SEDAN = 4,
    gate_v1_VehicleClass_VEHICLE_CLASS_SUV = 5,
    gate_v1_VehicleClass_VEHICLE_CLASS_PICKUP = 6,
    gate_v1_VehicleClass_VEHICLE_CLASS_VAN = 7,
    gate_v1_VehicleClass_VEHICLE_CLASS_TRUCK = 8
} gate_v1_VehicleClass;

/* GateState — the only legal states. Matches the state machine in
 docs/diagrams/05-gate-state-machine.mmd. Transitions are server-authoritative
 but firmware reports actual hardware state via Telemetry. */
typedef enum _gate_v1_GateState {
    gate_v1_GateState_GATE_STATE_UNKNOWN = 0,
    gate_v1_GateState_GATE_STATE_CLOSED = 1, /* Both limit switches show closed */
    gate_v1_GateState_GATE_STATE_OPENING = 2, /* Trigger fired, no limit switch yet */
    gate_v1_GateState_GATE_STATE_OPEN = 3, /* Open limit switch active */
    gate_v1_GateState_GATE_STATE_CLOSING = 4, /* Auto-close timer expired, motor reversing */
    gate_v1_GateState_GATE_STATE_FAULT = 5, /* Limit switch stuck, motor timeout, beam blocked */
    gate_v1_GateState_GATE_STATE_LOCKDOWN = 6 /* Force-close override active */
} gate_v1_GateState;

/* AuthVerdict — final fusion engine decision per
 docs/diagrams/04-fusion-decision.mmd. */
typedef enum _gate_v1_AuthVerdict {
    gate_v1_AuthVerdict_AUTH_VERDICT_UNSPECIFIED = 0,
    gate_v1_AuthVerdict_AUTH_VERDICT_AUTHORIZED = 1, /* Open the gate */
    gate_v1_AuthVerdict_AUTH_VERDICT_DENIED = 2, /* Hard deny — log + alert */
    gate_v1_AuthVerdict_AUTH_VERDICT_LOW_CONFIDENCE = 3, /* Below threshold — alert guard */
    gate_v1_AuthVerdict_AUTH_VERDICT_MANUAL_REVIEW = 4 /* Allowlist hit but class mismatch */
} gate_v1_AuthVerdict;

/* DenyReason — only meaningful when verdict == DENIED or LOW_CONFIDENCE. */
typedef enum _gate_v1_DenyReason {
    gate_v1_DenyReason_DENY_REASON_NONE = 0,
    gate_v1_DenyReason_DENY_REASON_BLOCKLISTED = 1,
    gate_v1_DenyReason_DENY_REASON_NOT_ON_ALLOWLIST = 2,
    gate_v1_DenyReason_DENY_REASON_OUTSIDE_WINDOW = 3,
    gate_v1_DenyReason_DENY_REASON_FORCE_CLOSE = 4,
    gate_v1_DenyReason_DENY_REASON_LOW_ALPR_CONF = 5,
    gate_v1_DenyReason_DENY_REASON_LOW_LIDAR_CONF = 6,
    gate_v1_DenyReason_DENY_REASON_CLASS_MISMATCH = 7,
    gate_v1_DenyReason_DENY_REASON_NO_PLATE_FOUND = 8,
    gate_v1_DenyReason_DENY_REASON_DUPLICATE_ENTRY = 9 /* Anti-tailgating */
} gate_v1_DenyReason;

/* CommandKind — every imperative the server sends to the field PCB. */
typedef enum _gate_v1_CommandKind {
    gate_v1_CommandKind_COMMAND_KIND_UNSPECIFIED = 0,
    gate_v1_CommandKind_COMMAND_KIND_OPEN_GATE = 1,
    gate_v1_CommandKind_COMMAND_KIND_CLOSE_GATE = 2,
    gate_v1_CommandKind_COMMAND_KIND_PULSE_RELAY = 3, /* Single trigger pulse (default mode) */
    gate_v1_CommandKind_COMMAND_KIND_LATCH_OPEN = 4, /* Force open until released */
    gate_v1_CommandKind_COMMAND_KIND_LATCH_CLOSE = 5, /* Lockdown */
    gate_v1_CommandKind_COMMAND_KIND_RELEASE_LATCH = 6,
    gate_v1_CommandKind_COMMAND_KIND_REBOOT = 7,
    gate_v1_CommandKind_COMMAND_KIND_BEGIN_OTA = 8,
    gate_v1_CommandKind_COMMAND_KIND_LED_PATTERN = 9 /* Visual feedback (auth flash, fault blink) */
} gate_v1_CommandKind;

/* LedPattern — visual feedback patterns the firmware can render on the auth
 and fault LEDs. Matches the firmware led_strip module. */
typedef enum _gate_v1_LedPattern {
    gate_v1_LedPattern_LED_PATTERN_OFF = 0,
    gate_v1_LedPattern_LED_PATTERN_AUTH_FLASH = 1, /* 3× green flash */
    gate_v1_LedPattern_LED_PATTERN_DENY_FLASH = 2, /* 3× red flash */
    gate_v1_LedPattern_LED_PATTERN_FAULT_SLOW = 3, /* 1Hz red blink */
    gate_v1_LedPattern_LED_PATTERN_OTA_PULSE = 4, /* Yellow pulse during update */
    gate_v1_LedPattern_LED_PATTERN_BOOT_OK = 5 /* Solid green for 2s on boot */
} gate_v1_LedPattern;

/* Severity for FaultEvent. */
typedef enum _gate_v1_FaultSeverity {
    gate_v1_FaultSeverity_FAULT_SEVERITY_UNSPECIFIED = 0,
    gate_v1_FaultSeverity_FAULT_SEVERITY_INFO = 1,
    gate_v1_FaultSeverity_FAULT_SEVERITY_WARN = 2,
    gate_v1_FaultSeverity_FAULT_SEVERITY_ERROR = 3,
    gate_v1_FaultSeverity_FAULT_SEVERITY_CRITICAL = 4
} gate_v1_FaultSeverity;

typedef enum _gate_v1_OtaProgress_OtaPhase {
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_UNKNOWN = 0,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_DOWNLOADING = 1,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_VERIFYING = 2,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_INSTALLING = 3,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_REBOOTING = 4,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_COMPLETE = 5,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_FAILED = 6,
    gate_v1_OtaProgress_OtaPhase_OTA_PHASE_ROLLED_BACK = 7
} gate_v1_OtaProgress_OtaPhase;

/* Struct definitions */
/* Pixel-space bounding box. Coordinates are absolute pixels in the camera's
 native resolution (Hikvision DS-2CD2043G2-I default 2560x1440). */
typedef struct _gate_v1_BoundingBox {
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
} gate_v1_BoundingBox;

/* World-space 3D position relative to the LiDAR origin (forward-X, left-Y,
 up-Z, ROS REP-103 convention). Units: meters. */
typedef struct _gate_v1_Point3D {
    float x;
    float y;
    float z;
} gate_v1_Point3D;

/* 3D oriented bounding box from the LiDAR detector. */
typedef struct _gate_v1_BoundingBox3D {
    bool has_center;
    gate_v1_Point3D center;
    float length; /* X dimension, meters */
    float width; /* Y dimension, meters */
    float height; /* Z dimension, meters */
    float yaw_radians; /* Rotation about Z (heading) */
} gate_v1_BoundingBox3D;

/* Single ALPR result for one detected plate. The full ALPR pipeline output
 (plate detection + OCR) is collapsed into this message. */
typedef struct _gate_v1_PlateDetection {
    pb_callback_t plate_text; /* OCR result, normalized uppercase, no spaces */
    float detection_conf; /* YOLOv9 confidence [0.0, 1.0] */
    float ocr_conf; /* PaddleOCR mean character confidence */
    bool has_box;
    gate_v1_BoundingBox box;
    pb_callback_t country_hint; /* ISO-3166 alpha-2, "" if unknown */
    pb_callback_t raw_ocr; /* Pre-normalization OCR text (for audit) */
} gate_v1_PlateDetection;

/* Single LiDAR detection. */
typedef struct _gate_v1_VehicleDetection {
    /* Named vehicle_class (not `class`): the C++ keyword forces protoc
 into escaped class_() accessors and breaks nanopb's C++-consumed
 headers outright. Same field number — wire-compatible rename. */
    gate_v1_VehicleClass vehicle_class;
    float class_conf; /* [0.0, 1.0] */
    bool has_box;
    gate_v1_BoundingBox3D box;
    bool has_velocity_mps;
    gate_v1_Point3D velocity_mps; /* Tracked velocity, m/s */
    uint32_t track_id; /* Stable ID across frames (0 if untracked) */
    uint32_t point_count; /* Number of LiDAR points in this cluster */
} gate_v1_VehicleDetection;

/* Snapshot of one detection cycle from both sensor pipelines. The server
 builds this from independent ALPR and LiDAR streams and feeds it to the
 fusion engine. */
typedef struct _gate_v1_DetectionFrame {
    bool has_capture_ts;
    google_protobuf_Timestamp capture_ts; /* Earliest sensor timestamp */
    uint64_t frame_id; /* Monotonic per gate_id */
    pb_callback_t gate_id;
    pb_callback_t plates;
    pb_callback_t vehicles;
    pb_callback_t camera_image_uri; /* Optional URI to JPEG snapshot */
    pb_callback_t lidar_pcd_uri; /* Optional URI to point cloud */
} gate_v1_DetectionFrame;

/* Request from server to fusion engine. Server-internal but defined here so
 simulation and tests can drive the engine directly. */
typedef struct _gate_v1_AuthorizeRequest {
    bool has_frame;
    gate_v1_DetectionFrame frame;
    pb_callback_t site_id; /* Multi-tenant key */
    bool override_allowlist; /* Guard manual approval */
    pb_callback_t actor; /* "auto" / username for audit */
} gate_v1_AuthorizeRequest;

/* Final decision delivered to firmware and dashboard. */
typedef struct _gate_v1_AuthDecision {
    pb_callback_t decision_id; /* UUIDv4 */
    bool has_decision_ts;
    google_protobuf_Timestamp decision_ts;
    pb_callback_t gate_id;
    gate_v1_AuthVerdict verdict;
    gate_v1_DenyReason deny_reason; /* Only set when not authorized */
    pb_callback_t matched_plate; /* Empty if no match */
    gate_v1_VehicleClass matched_class;
    float combined_conf; /* w1*alpr + w2*lidar */
    pb_callback_t reason_text; /* Human-readable for UI */
    uint64_t frame_id; /* Backref to DetectionFrame */
    pb_callback_t actor;
} gate_v1_AuthDecision;

/* Once per second from the firmware. Lightweight — keep payload small to
 minimize cellular fallback bandwidth. */
typedef struct _gate_v1_Telemetry {
    char gate_id[32];
    bool has_sent_ts;
    google_protobuf_Timestamp sent_ts;
    gate_v1_GateState gate_state;
    bool limit_open;
    bool limit_closed;
    bool safety_beam_clear;
    uint32_t uptime_sec;
    int32_t rssi_dbm; /* Wifi RSSI, 0 if wired */
    uint32_t free_heap_bytes;
    uint32_t min_free_heap; /* Watermark since boot */
    float supply_voltage_v; /* Measured 12V rail */
    float core_temp_c;
    char firmware_version[24]; /* SemVer string */
    char firmware_sha256[65]; /* Hex digest of running image */
    uint64_t seq; /* Monotonic counter */
} gate_v1_Telemetry;

typedef PB_BYTES_ARRAY_T(64) gate_v1_GateCommand_signature_t;
/* Server → firmware command. */
typedef struct _gate_v1_GateCommand {
    char command_id[40]; /* UUIDv4 — firmware echoes in ack */
    bool has_issued_ts;
    google_protobuf_Timestamp issued_ts;
    char gate_id[32];
    gate_v1_CommandKind kind;
    bool has_duration;
    google_protobuf_Duration duration; /* For pulse / latch operations */
    gate_v1_LedPattern led_pattern; /* Only for COMMAND_KIND_LED_PATTERN */
    uint32_t relay_index; /* 0-3, default 0 (leaf 1) */
    char actor[48]; /* For audit log */
    gate_v1_GateCommand_signature_t signature; /* Optional ed25519 over hash */
} gate_v1_GateCommand;

/* Firmware → server acknowledgement of a command. Sent immediately on receipt
 (with completed=false) and again when execution finishes. */
typedef struct _gate_v1_CommandAck {
    char command_id[40];
    bool has_received_ts;
    google_protobuf_Timestamp received_ts;
    bool has_completed_ts;
    google_protobuf_Timestamp completed_ts; /* Zero until finished */
    bool completed;
    bool success;
    char error_text[96]; /* Populated only when !success */
    gate_v1_GateState state_after;
} gate_v1_CommandAck;

typedef struct _gate_v1_FaultEvent_ContextEntry {
    char key[24];
    char value[48];
} gate_v1_FaultEvent_ContextEntry;

typedef struct _gate_v1_FaultEvent {
    char fault_id[40]; /* UUIDv4 */
    bool has_occurred_ts;
    google_protobuf_Timestamp occurred_ts;
    char gate_id[32];
    gate_v1_FaultSeverity severity;
    char code[32]; /* e.g., "MOTOR_TIMEOUT" */
    char description[96]; /* Human-readable */
    pb_size_t context_count;
    gate_v1_FaultEvent_ContextEntry context[4]; /* Free-form k/v */
} gate_v1_FaultEvent;

typedef PB_BYTES_ARRAY_T(64) gate_v1_OtaManifest_ed25519_sig_t;
typedef struct _gate_v1_OtaManifest {
    char target_version[24]; /* SemVer */
    char image_sha256[65]; /* Hex */
    uint64_t image_size; /* Bytes */
    gate_v1_OtaManifest_ed25519_sig_t ed25519_sig; /* Signature over manifest+image */
    char signing_key_id[32];
    bool has_built_ts;
    google_protobuf_Timestamp built_ts;
    char release_notes[128]; /* URL or short text */
    uint32_t min_uptime_sec; /* Refuse update if uptime < this (production safety) */
} gate_v1_OtaManifest;

typedef PB_BYTES_ARRAY_T(4096) gate_v1_OtaChunk_data_t;
typedef struct _gate_v1_OtaChunk {
    uint64_t offset;
    gate_v1_OtaChunk_data_t data; /* Up to 4096 bytes per chunk (ESP32 flash sector) */
    /* Named is_final (not `final`): protobuf's C++ keyword-escaping for
 `final` changed across protoc versions (final_() → final()), which
 makes generated-API stability depend on the toolchain. Same field
 number, so the rename is wire-compatible. */
    bool is_final; /* True on last chunk */
} gate_v1_OtaChunk;

typedef struct _gate_v1_OtaProgress {
    char command_id[40];
    uint64_t bytes_received;
    uint64_t bytes_total;
    gate_v1_OtaProgress_OtaPhase phase;
    pb_callback_t message; /* Optional human description */
} gate_v1_OtaProgress;

typedef struct _gate_v1_DashboardEvent {
    uint64_t event_id; /* Monotonic per server boot */
    bool has_event_ts;
    google_protobuf_Timestamp event_ts;
    pb_size_t which_payload;
    union {
        gate_v1_AuthDecision decision;
        gate_v1_Telemetry telemetry;
        gate_v1_FaultEvent fault;
        gate_v1_OtaProgress ota;
        gate_v1_GateCommand command;
        gate_v1_CommandAck ack;
    } payload;
} gate_v1_DashboardEvent;

/* Filter the dashboard subscription by site/gate. */
typedef struct _gate_v1_DashboardSubscription {
    pb_callback_t site_id; /* Empty = all */
    pb_callback_t gate_ids; /* Empty = all */
    bool include_decisions;
    bool include_telemetry;
    bool include_faults;
    bool include_ota;
    uint64_t since_event_id; /* Replay events after this */
} gate_v1_DashboardSubscription;

typedef struct _gate_v1_TimeWindow {
    uint32_t start_minute_of_day; /* 0..1439, local time */
    uint32_t end_minute_of_day;
    uint32_t days_of_week_mask; /* bit0=Mon ... bit6=Sun */
} gate_v1_TimeWindow;

typedef struct _gate_v1_Allowlistentry {
    pb_callback_t plate_text; /* Normalized uppercase */
    pb_callback_t allowed_classes; /* Empty = any class allowed */
    pb_callback_t time_windows; /* Empty = always allowed */
    pb_callback_t owner_name;
    pb_callback_t owner_unit; /* Apartment/house number */
    bool has_valid_from;
    google_protobuf_Timestamp valid_from;
    bool has_valid_until;
    google_protobuf_Timestamp valid_until; /* Zero = no expiry */
    pb_callback_t notes;
    pb_callback_t added_by;
    bool has_added_ts;
    google_protobuf_Timestamp added_ts;
} gate_v1_Allowlistentry;

typedef struct _gate_v1_UpsertAllowlistRequest {
    pb_callback_t site_id;
    pb_callback_t entries;
} gate_v1_UpsertAllowlistRequest;

typedef struct _gate_v1_UpsertAllowlistResponse {
    uint32_t inserted;
    uint32_t updated;
} gate_v1_UpsertAllowlistResponse;

typedef struct _gate_v1_ListAllowlistRequest {
    pb_callback_t site_id;
    uint32_t page_size;
    pb_callback_t page_token;
} gate_v1_ListAllowlistRequest;

typedef struct _gate_v1_ListAllowlistResponse {
    pb_callback_t entries;
    pb_callback_t next_page_token;
} gate_v1_ListAllowlistResponse;

typedef struct _gate_v1_DeleteAllowlistRequest {
    pb_callback_t site_id;
    pb_callback_t plate_texts;
} gate_v1_DeleteAllowlistRequest;

/* ControlEnvelope multiplexes the bidirectional Control stream. Exactly one
 payload set per envelope. */
typedef struct _gate_v1_ControlEnvelope {
    pb_size_t which_payload;
    union {
        gate_v1_Telemetry telemetry;
        gate_v1_CommandAck ack;
        gate_v1_FaultEvent fault;
        gate_v1_GateCommand command; /* Only ever populated by server */
    } payload;
} gate_v1_ControlEnvelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _gate_v1_VehicleClass_MIN gate_v1_VehicleClass_VEHICLE_CLASS_UNKNOWN
#define _gate_v1_VehicleClass_MAX gate_v1_VehicleClass_VEHICLE_CLASS_TRUCK
#define _gate_v1_VehicleClass_ARRAYSIZE ((gate_v1_VehicleClass)(gate_v1_VehicleClass_VEHICLE_CLASS_TRUCK+1))

#define _gate_v1_GateState_MIN gate_v1_GateState_GATE_STATE_UNKNOWN
#define _gate_v1_GateState_MAX gate_v1_GateState_GATE_STATE_LOCKDOWN
#define _gate_v1_GateState_ARRAYSIZE ((gate_v1_GateState)(gate_v1_GateState_GATE_STATE_LOCKDOWN+1))

#define _gate_v1_AuthVerdict_MIN gate_v1_AuthVerdict_AUTH_VERDICT_UNSPECIFIED
#define _gate_v1_AuthVerdict_MAX gate_v1_AuthVerdict_AUTH_VERDICT_MANUAL_REVIEW
#define _gate_v1_AuthVerdict_ARRAYSIZE ((gate_v1_AuthVerdict)(gate_v1_AuthVerdict_AUTH_VERDICT_MANUAL_REVIEW+1))

#define _gate_v1_DenyReason_MIN gate_v1_DenyReason_DENY_REASON_NONE
#define _gate_v1_DenyReason_MAX gate_v1_DenyReason_DENY_REASON_DUPLICATE_ENTRY
#define _gate_v1_DenyReason_ARRAYSIZE ((gate_v1_DenyReason)(gate_v1_DenyReason_DENY_REASON_DUPLICATE_ENTRY+1))

#define _gate_v1_CommandKind_MIN gate_v1_CommandKind_COMMAND_KIND_UNSPECIFIED
#define _gate_v1_CommandKind_MAX gate_v1_CommandKind_COMMAND_KIND_LED_PATTERN
#define _gate_v1_CommandKind_ARRAYSIZE ((gate_v1_CommandKind)(gate_v1_CommandKind_COMMAND_KIND_LED_PATTERN+1))

#define _gate_v1_LedPattern_MIN gate_v1_LedPattern_LED_PATTERN_OFF
#define _gate_v1_LedPattern_MAX gate_v1_LedPattern_LED_PATTERN_BOOT_OK
#define _gate_v1_LedPattern_ARRAYSIZE ((gate_v1_LedPattern)(gate_v1_LedPattern_LED_PATTERN_BOOT_OK+1))

#define _gate_v1_FaultSeverity_MIN gate_v1_FaultSeverity_FAULT_SEVERITY_UNSPECIFIED
#define _gate_v1_FaultSeverity_MAX gate_v1_FaultSeverity_FAULT_SEVERITY_CRITICAL
#define _gate_v1_FaultSeverity_ARRAYSIZE ((gate_v1_FaultSeverity)(gate_v1_FaultSeverity_FAULT_SEVERITY_CRITICAL+1))

#define _gate_v1_OtaProgress_OtaPhase_MIN gate_v1_OtaProgress_OtaPhase_OTA_PHASE_UNKNOWN
#define _gate_v1_OtaProgress_OtaPhase_MAX gate_v1_OtaProgress_OtaPhase_OTA_PHASE_ROLLED_BACK
#define _gate_v1_OtaProgress_OtaPhase_ARRAYSIZE ((gate_v1_OtaProgress_OtaPhase)(gate_v1_OtaProgress_OtaPhase_OTA_PHASE_ROLLED_BACK+1))





#define gate_v1_VehicleDetection_vehicle_class_ENUMTYPE gate_v1_VehicleClass



#define gate_v1_AuthDecision_verdict_ENUMTYPE gate_v1_AuthVerdict
#define gate_v1_AuthDecision_deny_reason_ENUMTYPE gate_v1_DenyReason
#define gate_v1_AuthDecision_matched_class_ENUMTYPE gate_v1_VehicleClass

#define gate_v1_Telemetry_gate_state_ENUMTYPE gate_v1_GateState

#define gate_v1_GateCommand_kind_ENUMTYPE gate_v1_CommandKind
#define gate_v1_GateCommand_led_pattern_ENUMTYPE gate_v1_LedPattern

#define gate_v1_CommandAck_state_after_ENUMTYPE gate_v1_GateState

#define gate_v1_FaultEvent_severity_ENUMTYPE gate_v1_FaultSeverity




#define gate_v1_OtaProgress_phase_ENUMTYPE gate_v1_OtaProgress_OtaPhase




#define gate_v1_Allowlistentry_allowed_classes_ENUMTYPE gate_v1_VehicleClass








/* Initializer values for message structs */
#define gate_v1_BoundingBox_init_default         {0, 0, 0, 0}
#define gate_v1_Point3D_init_default             {0, 0, 0}
#define gate_v1_BoundingBox3D_init_default       {false, gate_v1_Point3D_init_default, 0, 0, 0, 0}
#define gate_v1_PlateDetection_init_default      {{{NULL}, NULL}, 0, 0, false, gate_v1_BoundingBox_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_VehicleDetection_init_default    {_gate_v1_VehicleClass_MIN, 0, false, gate_v1_BoundingBox3D_init_default, false, gate_v1_Point3D_init_default, 0, 0}
#define gate_v1_DetectionFrame_init_default      {false, google_protobuf_Timestamp_init_default, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_AuthorizeRequest_init_default    {false, gate_v1_DetectionFrame_init_default, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gate_v1_AuthDecision_init_default        {{{NULL}, NULL}, false, google_protobuf_Timestamp_init_default, {{NULL}, NULL}, _gate_v1_AuthVerdict_MIN, _gate_v1_DenyReason_MIN, {{NULL}, NULL}, _gate_v1_VehicleClass_MIN, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gate_v1_Telemetry_init_default           {"", false, google_protobuf_Timestamp_init_default, _gate_v1_GateState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0}
#define gate_v1_GateCommand_init_default         {"", false, google_protobuf_Timestamp_init_default, "", _gate_v1_CommandKind_MIN, false, google_protobuf_Duration_init_default, _gate_v1_LedPattern_MIN, 0, "", {0, {0}}}
#define gate_v1_CommandAck_init_default          {"", false, google_protobuf_Timestamp_init_default, false, google_protobuf_Timestamp_init_default, 0, 0, "", _gate_v1_GateState_MIN}
#define gate_v1_FaultEvent_init_default          {"", false, google_protobuf_Timestamp_init_default, "", _gate_v1_FaultSeverity_MIN, "", "", 0, {gate_v1_FaultEvent_ContextEntry_init_default, gate_v1_FaultEvent_ContextEntry_init_default, gate_v1_FaultEvent_ContextEntry_init_default, gate_v1_FaultEvent_ContextEntry_init_default}}
#define gate_v1_FaultEvent_ContextEntry_init_default {"", ""}
#define gate_v1_OtaManifest_init_default         {"", "", 0, {0, {0}}, "", false, google_protobuf_Timestamp_init_default, "", 0}
#define gate_v1_OtaChunk_init_default            {0, {0, {0}}, 0}
#define gate_v1_OtaProgress_init_default         {"", 0, 0, _gate_v1_OtaProgress_OtaPhase_MIN, {{NULL}, NULL}}
#define gate_v1_DashboardEvent_init_default      {0, false, google_protobuf_Timestamp_init_default, 0, {gate_v1_AuthDecision_init_default}}
#define gate_v1_DashboardSubscription_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0}
#define gate_v1_TimeWindow_init_default          {0, 0, 0}
#define gate_v1_Allowlistentry_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Timestamp_init_default, false, google_protobuf_Timestamp_init_default, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Timestamp_init_default}
#define gate_v1_UpsertAllowlistRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_UpsertAllowlistResponse_init_default {0, 0}
#define gate_v1_ListAllowlistRequest_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gate_v1_ListAllowlistResponse_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_DeleteAllowlistRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_ControlEnvelope_init_default     {0, {gate_v1_Telemetry_init_default}}
#define gate_v1_BoundingBox_init_zero            {0, 0, 0, 0}
#define gate_v1_Point3D_init_zero                {0, 0, 0}
#define gate_v1_BoundingBox3D_init_zero          {false, gate_v1_Point3D_init_zero, 0, 0, 0, 0}
#define gate_v1_PlateDetection_init_zero         {{{NULL}, NULL}, 0, 0, false, gate_v1_BoundingBox_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_VehicleDetection_init_zero       {_gate_v1_VehicleClass_MIN, 0, false, gate_v1_BoundingBox3D_init_zero, false, gate_v1_Point3D_init_zero, 0, 0}
#define gate_v1_DetectionFrame_init_zero         {false, google_protobuf_Timestamp_init_zero, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_AuthorizeRequest_init_zero       {false, gate_v1_DetectionFrame_init_zero, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gate_v1_AuthDecision_init_zero           {{{NULL}, NULL}, false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL}, _gate_v1_AuthVerdict_MIN, _gate_v1_DenyReason_MIN, {{NULL}, NULL}, _gate_v1_VehicleClass_MIN, 0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gate_v1_Telemetry_init_zero              {"", false, google_protobuf_Timestamp_init_zero, _gate_v1_GateState_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0}
#define gate_v1_GateCommand_init_zero            {"", false, google_protobuf_Timestamp_init_zero, "", _gate_v1_CommandKind_MIN, false, google_protobuf_Duration_init_zero, _gate_v1_LedPattern_MIN, 0, "", {0, {0}}}
#define gate_v1_CommandAck_init_zero             {"", false, google_protobuf_Timestamp_init_zero, false, google_protobuf_Timestamp_init_zero, 0, 0, "", _gate_v1_GateState_MIN}
#define gate_v1_FaultEvent_init_zero             {"", false, google_protobuf_Timestamp_init_zero, "", _gate_v1_FaultSeverity_MIN, "", "", 0, {gate_v1_FaultEvent_ContextEntry_init_zero, gate_v1_FaultEvent_ContextEntry_init_zero, gate_v1_FaultEvent_ContextEntry_init_zero, gate_v1_FaultEvent_ContextEntry_init_zero}}
#define gate_v1_FaultEvent_ContextEntry_init_zero {"", ""}
#define gate_v1_OtaManifest_init_zero            {"", "", 0, {0, {0}}, "", false, google_protobuf_Timestamp_init_zero, "", 0}
#define gate_v1_OtaChunk_init_zero               {0, {0, {0}}, 0}
#define gate_v1_OtaProgress_init_zero            {"", 0, 0, _gate_v1_OtaProgress_OtaPhase_MIN, {{NULL}, NULL}}
#define gate_v1_DashboardEvent_init_zero         {0, false, google_protobuf_Timestamp_init_zero, 0, {gate_v1_AuthDecision_init_zero}}
#define gate_v1_DashboardSubscription_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0}
#define gate_v1_TimeWindow_init_zero             {0, 0, 0}
#define gate_v1_Allowlistentry_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Timestamp_init_zero, false, google_protobuf_Timestamp_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, false, google_protobuf_Timestamp_init_zero}
#define gate_v1_UpsertAllowlistRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_UpsertAllowlistResponse_init_zero {0, 0}
#define gate_v1_ListAllowlistRequest_init_zero   {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define gate_v1_ListAllowlistResponse_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_DeleteAllowlistRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define gate_v1_ControlEnvelope_init_zero        {0, {gate_v1_Telemetry_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define gate_v1_BoundingBox_x_tag                1
#define gate_v1_BoundingBox_y_tag                2
#define gate_v1_BoundingBox_width_tag            3
#define gate_v1_BoundingBox_height_tag           4
#define gate_v1_Point3D_x_tag                    1
#define gate_v1_Point3D_y_tag                    2
#define gate_v1_Point3D_z_tag                    3
#define gate_v1_BoundingBox3D_center_tag         1
#define gate_v1_BoundingBox3D_length_tag         2
#define gate_v1_BoundingBox3D_width_tag          3
#define gate_v1_BoundingBox3D_height_tag         4
#define gate_v1_BoundingBox3D_yaw_radians_tag    5
#define gate_v1_PlateDetection_plate_text_tag    1
#define gate_v1_PlateDetection_detection_conf_tag 2
#define gate_v1_PlateDetection_ocr_conf_tag      3
#define gate_v1_PlateDetection_box_tag           4
#define gate_v1_PlateDetection_country_hint_tag  5
#define gate_v1_PlateDetection_raw_ocr_tag       6
#define gate_v1_VehicleDetection_vehicle_class_tag 1
#define gate_v1_VehicleDetection_class_conf_tag  2
#define gate_v1_VehicleDetection_box_tag         3
#define gate_v1_VehicleDetection_velocity_mps_tag 4
#define gate_v1_VehicleDetection_track_id_tag    5
#define gate_v1_VehicleDetection_point_count_tag 6
#define gate_v1_DetectionFrame_capture_ts_tag    1
#define gate_v1_DetectionFrame_frame_id_tag      2
#define gate_v1_DetectionFrame_gate_id_tag       3
#define gate_v1_DetectionFrame_plates_tag        4
#define gate_v1_DetectionFrame_vehicles_tag      5
#define gate_v1_DetectionFrame_camera_image_uri_tag 6
#define gate_v1_DetectionFrame_lidar_pcd_uri_tag 7
#define gate_v1_AuthorizeRequest_frame_tag       1
#define gate_v1_AuthorizeRequest_site_id_tag     2
#define gate_v1_AuthorizeRequest_override_allowlist_tag 3
#define gate_v1_AuthorizeRequest_actor_tag       4
#define gate_v1_AuthDecision_decision_id_tag     1
#define gate_v1_AuthDecision_decision_ts_tag     2
#define gate_v1_AuthDecision_gate_id_tag         3
#define gate_v1_AuthDecision_verdict_tag         4
#define gate_v1_AuthDecision_deny_reason_tag     5
#define gate_v1_AuthDecision_matched_plate_tag   6
#define gate_v1_AuthDecision_matched_class_tag   7
#define gate_v1_AuthDecision_combined_conf_tag   8
#define gate_v1_AuthDecision_reason_text_tag     9
#define gate_v1_AuthDecision_frame_id_tag        10
#define gate_v1_AuthDecision_actor_tag           11
#define gate_v1_Telemetry_gate_id_tag            1
#define gate_v1_Telemetry_sent_ts_tag            2
#define gate_v1_Telemetry_gate_state_tag         3
#define gate_v1_Telemetry_limit_open_tag         4
#define gate_v1_Telemetry_limit_closed_tag       5
#define gate_v1_Telemetry_safety_beam_clear_tag  6
#define gate_v1_Telemetry_uptime_sec_tag         7
#define gate_v1_Telemetry_rssi_dbm_tag           8
#define gate_v1_Telemetry_free_heap_bytes_tag    9
#define gate_v1_Telemetry_min_free_heap_tag      10
#define gate_v1_Telemetry_supply_voltage_v_tag   11
#define gate_v1_Telemetry_core_temp_c_tag        12
#define gate_v1_Telemetry_firmware_version_tag   13
#define gate_v1_Telemetry_firmware_sha256_tag    14
#define gate_v1_Telemetry_seq_tag                15
#define gate_v1_GateCommand_command_id_tag       1
#define gate_v1_GateCommand_issued_ts_tag        2
#define gate_v1_GateCommand_gate_id_tag          3
#define gate_v1_GateCommand_kind_tag             4
#define gate_v1_GateCommand_duration_tag         5
#define gate_v1_GateCommand_led_pattern_tag      6
#define gate_v1_GateCommand_relay_index_tag      7
#define gate_v1_GateCommand_actor_tag            8
#define gate_v1_GateCommand_signature_tag        9
#define gate_v1_CommandAck_command_id_tag        1
#define gate_v1_CommandAck_received_ts_tag       2
#define gate_v1_CommandAck_completed_ts_tag      3
#define gate_v1_CommandAck_completed_tag         4
#define gate_v1_CommandAck_success_tag           5
#define gate_v1_CommandAck_error_text_tag        6
#define gate_v1_CommandAck_state_after_tag       7
#define gate_v1_FaultEvent_ContextEntry_key_tag  1
#define gate_v1_FaultEvent_ContextEntry_value_tag 2
#define gate_v1_FaultEvent_fault_id_tag          1
#define gate_v1_FaultEvent_occurred_ts_tag       2
#define gate_v1_FaultEvent_gate_id_tag           3
#define gate_v1_FaultEvent_severity_tag          4
#define gate_v1_FaultEvent_code_tag              5
#define gate_v1_FaultEvent_description_tag       6
#define gate_v1_FaultEvent_context_tag           7
#define gate_v1_OtaManifest_target_version_tag   1
#define gate_v1_OtaManifest_image_sha256_tag     2
#define gate_v1_OtaManifest_image_size_tag       3
#define gate_v1_OtaManifest_ed25519_sig_tag      4
#define gate_v1_OtaManifest_signing_key_id_tag   5
#define gate_v1_OtaManifest_built_ts_tag         6
#define gate_v1_OtaManifest_release_notes_tag    7
#define gate_v1_OtaManifest_min_uptime_sec_tag   8
#define gate_v1_OtaChunk_offset_tag              1
#define gate_v1_OtaChunk_data_tag                2
#define gate_v1_OtaChunk_is_final_tag            3
#define gate_v1_OtaProgress_command_id_tag       1
#define gate_v1_OtaProgress_bytes_received_tag   2
#define gate_v1_OtaProgress_bytes_total_tag      3
#define gate_v1_OtaProgress_phase_tag            4
#define gate_v1_OtaProgress_message_tag          5
#define gate_v1_DashboardEvent_event_id_tag      1
#define gate_v1_DashboardEvent_event_ts_tag      2
#define gate_v1_DashboardEvent_decision_tag      3
#define gate_v1_DashboardEvent_telemetry_tag     4
#define gate_v1_DashboardEvent_fault_tag         5
#define gate_v1_DashboardEvent_ota_tag           6
#define gate_v1_DashboardEvent_command_tag       7
#define gate_v1_DashboardEvent_ack_tag           8
#define gate_v1_DashboardSubscription_site_id_tag 1
#define gate_v1_DashboardSubscription_gate_ids_tag 2
#define gate_v1_DashboardSubscription_include_decisions_tag 3
#define gate_v1_DashboardSubscription_include_telemetry_tag 4
#define gate_v1_DashboardSubscription_include_faults_tag 5
#define gate_v1_DashboardSubscription_include_ota_tag 6
#define gate_v1_DashboardSubscription_since_event_id_tag 7
#define gate_v1_TimeWindow_start_minute_of_day_tag 1
#define gate_v1_TimeWindow_end_minute_of_day_tag 2
#define gate_v1_TimeWindow_days_of_week_mask_tag 3
#define gate_v1_Allowlistentry_plate_text_tag    1
#define gate_v1_Allowlistentry_allowed_classes_tag 2
#define gate_v1_Allowlistentry_time_windows_tag  3
#define gate_v1_Allowlistentry_owner_name_tag    4
#define gate_v1_Allowlistentry_owner_unit_tag    5
#define gate_v1_Allowlistentry_valid_from_tag    6
#define gate_v1_Allowlistentry_valid_until_tag   7
#define gate_v1_Allowlistentry_notes_tag         8
#define gate_v1_Allowlistentry_added_by_tag      9
#define gate_v1_Allowlistentry_added_ts_tag      10
#define gate_v1_UpsertAllowlistRequest_site_id_tag 1
#define gate_v1_UpsertAllowlistRequest_entries_tag 2
#define gate_v1_UpsertAllowlistResponse_inserted_tag 1
#define gate_v1_UpsertAllowlistResponse_updated_tag 2
#define gate_v1_ListAllowlistRequest_site_id_tag 1
#define gate_v1_ListAllowlistRequest_page_size_tag 2
#define gate_v1_ListAllowlistRequest_page_token_tag 3
#define gate_v1_ListAllowlistResponse_entries_tag 1
#define gate_v1_ListAllowlistResponse_next_page_token_tag 2
#define gate_v1_DeleteAllowlistRequest_site_id_tag 1
#define gate_v1_DeleteAllowlistRequest_plate_texts_tag 2
#define gate_v1_ControlEnvelope_telemetry_tag    1
#define gate_v1_ControlEnvelope_ack_tag          2
#define gate_v1_ControlEnvelope_fault_tag        3
#define gate_v1_ControlEnvelope_command_tag      4

/* Struct field encoding specification for nanopb */
#define gate_v1_BoundingBox_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   width,             3) \
X(a, STATIC,   SINGULAR, UINT32,   height,            4)
#define gate_v1_BoundingBox_CALLBACK NULL
#define gate_v1_BoundingBox_DEFAULT NULL

#define gate_v1_Point3D_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3)
#define gate_v1_Point3D_CALLBACK NULL
#define gate_v1_Point3D_DEFAULT NULL

#define gate_v1_BoundingBox3D_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  center,            1) \
X(a, STATIC,   SINGULAR, FLOAT,    length,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    width,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    height,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw_radians,       5)
#define gate_v1_BoundingBox3D_CALLBACK NULL
#define gate_v1_BoundingBox3D_DEFAULT NULL
#define gate_v1_BoundingBox3D_center_MSGTYPE gate_v1_Point3D

#define gate_v1_PlateDetection_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   plate_text,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    detection_conf,    2) \
X(a, STATIC,   SINGULAR, FLOAT,    ocr_conf,          3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  box,               4) \
X(a, CALLBACK, SINGULAR, STRING,   country_hint,      5) \
X(a, CALLBACK, SINGULAR, STRING,   raw_ocr,           6)
#define gate_v1_PlateDetection_CALLBACK pb_default_field_callback
#define gate_v1_PlateDetection_DEFAULT NULL
#define gate_v1_PlateDetection_box_MSGTYPE gate_v1_BoundingBox

#define gate_v1_VehicleDetection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    vehicle_class,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    class_conf,        2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  box,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  velocity_mps,      4) \
X(a, STATIC,   SINGULAR, UINT32,   track_id,          5) \
X(a, STATIC,   SINGULAR, UINT32,   point_count,       6)
#define gate_v1_VehicleDetection_CALLBACK NULL
#define gate_v1_VehicleDetection_DEFAULT NULL
#define gate_v1_VehicleDetection_box_MSGTYPE gate_v1_BoundingBox3D
#define gate_v1_VehicleDetection_velocity_mps_MSGTYPE gate_v1_Point3D

#define gate_v1_DetectionFrame_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  capture_ts,        1) \
X(a, STATIC,   SINGULAR, UINT64,   frame_id,          2) \
X(a, CALLBACK, SINGULAR, STRING,   gate_id,           3) \
X(a, CALLBACK, REPEATED, MESSAGE,  plates,            4) \
X(a, CALLBACK, REPEATED, MESSAGE,  vehicles,          5) \
X(a, CALLBACK, SINGULAR, STRING,   camera_image_uri,   6) \
X(a, CALLBACK, SINGULAR, STRING,   lidar_pcd_uri,     7)
#define gate_v1_DetectionFrame_CALLBACK pb_default_field_callback
#define gate_v1_DetectionFrame_DEFAULT NULL
#define gate_v1_DetectionFrame_capture_ts_MSGTYPE google_protobuf_Timestamp
#define gate_v1_DetectionFrame_plates_MSGTYPE gate_v1_PlateDetection
#define gate_v1_DetectionFrame_vehicles_MSGTYPE gate_v1_VehicleDetection

#define gate_v1_AuthorizeRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  frame,             1) \
X(a, CALLBACK, SINGULAR, STRING,   site_id,           2) \
X(a, STATIC,   SINGULAR, BOOL,     override_allowlist,   3) \
X(a, CALLBACK, SINGULAR, STRING,   actor,             4)
#define gate_v1_AuthorizeRequest_CALLBACK pb_default_field_callback
#define gate_v1_AuthorizeRequest_DEFAULT NULL
#define gate_v1_AuthorizeRequest_frame_MSGTYPE gate_v1_DetectionFrame

#define gate_v1_AuthDecision_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   decision_id,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  decision_ts,       2) \
X(a, CALLBACK, SINGULAR, STRING,   gate_id,           3) \
X(a, STATIC,   SINGULAR, UENUM,    verdict,           4) \
X(a, STATIC,   SINGULAR, UENUM,    deny_reason,       5) \
X(a, CALLBACK, SINGULAR, STRING,   matched_plate,     6) \
X(a, STATIC,   SINGULAR, UENUM,    matched_class,     7) \
X(a, STATIC,   SINGULAR, FLOAT,    combined_conf,     8) \
X(a, CALLBACK, SINGULAR, STRING,   reason_text,       9) \
X(a, STATIC,   SINGULAR, UINT64,   frame_id,         10) \
X(a, CALLBACK, SINGULAR, STRING,   actor,            11)
#define gate_v1_AuthDecision_CALLBACK pb_default_field_callback
#define gate_v1_AuthDecision_DEFAULT NULL
#define gate_v1_AuthDecision_decision_ts_MSGTYPE google_protobuf_Timestamp

#define gate_v1_Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   gate_id,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sent_ts,           2) \
X(a, STATIC,   SINGULAR, UENUM,    gate_state,        3) \
X(a, STATIC,   SINGULAR, BOOL,     limit_open,        4) \
X(a, STATIC,   SINGULAR, BOOL,     limit_closed,      5) \
X(a, STATIC,   SINGULAR, BOOL,     safety_beam_clear,   6) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_sec,        7) \
X(a, STATIC,   SINGULAR, INT32,    rssi_dbm,          8) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap_bytes,   9) \
X(a, STATIC,   SINGULAR, UINT32,   min_free_heap,    10) \
X(a, STATIC,   SINGULAR, FLOAT,    supply_voltage_v,  11) \
X(a, STATIC,   SINGULAR, FLOAT,    core_temp_c,      12) \
X(a, STATIC,   SINGULAR, STRING,   firmware_version,  13) \
X(a, STATIC,   SINGULAR, STRING,   firmware_sha256,  14) \
X(a, STATIC,   SINGULAR, UINT64,   seq,              15)
#define gate_v1_Telemetry_CALLBACK NULL
#define gate_v1_Telemetry_DEFAULT NULL
#define gate_v1_Telemetry_sent_ts_MSGTYPE google_protobuf_Timestamp

#define gate_v1_GateCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  issued_ts,         2) \
X(a, STATIC,   SINGULAR, STRING,   gate_id,           3) \
X(a, STATIC,   SINGULAR, UENUM,    kind,              4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  duration,          5) \
X(a, STATIC,   SINGULAR, UENUM,    led_pattern,       6) \
X(a, STATIC,   SINGULAR, UINT32,   relay_index,       7) \
X(a, STATIC,   SINGULAR, STRING,   actor,             8) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         9)
#define gate_v1_GateCommand_CALLBACK NULL
#define gate_v1_GateCommand_DEFAULT NULL
#define gate_v1_GateCommand_issued_ts_MSGTYPE google_protobuf_Timestamp
#define gate_v1_GateCommand_duration_MSGTYPE google_protobuf_Duration

#define gate_v1_CommandAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  received_ts,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  completed_ts,      3) \
X(a, STATIC,   SINGULAR, BOOL,     completed,         4) \
X(a, STATIC,   SINGULAR, BOOL,     success,           5) \
X(a, STATIC,   SINGULAR, STRING,   error_text,        6) \
X(a, STATIC,   SINGULAR, UENUM,    state_after,       7)
#define gate_v1_CommandAck_CALLBACK NULL
#define gate_v1_CommandAck_DEFAULT NULL
#define gate_v1_CommandAck_received_ts_MSGTYPE google_protobuf_Timestamp
#define gate_v1_CommandAck_completed_ts_MSGTYPE google_protobuf_Timestamp

#define gate_v1_FaultEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   fault_id,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  occurred_ts,       2) \
X(a, STATIC,   SINGULAR, STRING,   gate_id,           3) \
X(a, STATIC,   SINGULAR, UENUM,    severity,          4) \
X(a, STATIC,   SINGULAR, STRING,   code,              5) \
X(a, STATIC,   SINGULAR, STRING,   description,       6) \
X(a, STATIC,   REPEATED, MESSAGE,  context,           7)
#define gate_v1_FaultEvent_CALLBACK NULL
#define gate_v1_FaultEvent_DEFAULT NULL
#define gate_v1_FaultEvent_occurred_ts_MSGTYPE google_protobuf_Timestamp
#define gate_v1_FaultEvent_context_MSGTYPE gate_v1_FaultEvent_ContextEntry

#define gate_v1_FaultEvent_ContextEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, STRING,   value,             2)
#define gate_v1_FaultEvent_ContextEntry_CALLBACK NULL
#define gate_v1_FaultEvent_ContextEntry_DEFAULT NULL

#define gate_v1_OtaManifest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   target_version,    1) \
X(a, STATIC,   SINGULAR, STRING,   image_sha256,      2) \
X(a, STATIC,   SINGULAR, UINT64,   image_size,        3) \
X(a, STATIC,   SINGULAR, BYTES,    ed25519_sig,       4) \
X(a, STATIC,   SINGULAR, STRING,   signing_key_id,    5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  built_ts,          6) \
X(a, STATIC,   SINGULAR, STRING,   release_notes,     7) \
X(a, STATIC,   SINGULAR, UINT32,   min_uptime_sec,    8)
#define gate_v1_OtaManifest_CALLBACK NULL
#define gate_v1_OtaManifest_DEFAULT NULL
#define gate_v1_OtaManifest_built_ts_MSGTYPE google_protobuf_Timestamp

#define gate_v1_OtaChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   offset,            1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2) \
X(a, STATIC,   SINGULAR, BOOL,     is_final,          3)
#define gate_v1_OtaChunk_CALLBACK NULL
#define gate_v1_OtaChunk_DEFAULT NULL

#define gate_v1_OtaProgress_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_received,    2) \
X(a, STATIC,   SINGULAR, UINT64,   bytes_total,       3) \
X(a, STATIC,   SINGULAR, UENUM,    phase,             4) \
X(a, CALLBACK, SINGULAR, STRING,   message,           5)
#define gate_v1_OtaProgress_CALLBACK pb_default_field_callback
#define gate_v1_OtaProgress_DEFAULT NULL

#define gate_v1_DashboardEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   event_id,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  event_ts,          2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,decision,payload.decision),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fault,payload.fault),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota,payload.ota),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command,payload.command),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   8)
#define gate_v1_DashboardEvent_CALLBACK NULL
#define gate_v1_DashboardEvent_DEFAULT NULL
#define gate_v1_DashboardEvent_event_ts_MSGTYPE google_protobuf_Timestamp
#define gate_v1_DashboardEvent_payload_decision_MSGTYPE gate_v1_AuthDecision
#define gate_v1_DashboardEvent_payload_telemetry_MSGTYPE gate_v1_Telemetry
#define gate_v1_DashboardEvent_payload_fault_MSGTYPE gate_v1_FaultEvent
#define gate_v1_DashboardEvent_payload_ota_MSGTYPE gate_v1_OtaProgress
#define gate_v1_DashboardEvent_payload_command_MSGTYPE gate_v1_GateCommand
#define gate_v1_DashboardEvent_payload_ack_MSGTYPE gate_v1_CommandAck

#define gate_v1_DashboardSubscription_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   site_id,           1) \
X(a, CALLBACK, REPEATED, STRING,   gate_ids,          2) \
X(a, STATIC,   SINGULAR, BOOL,     include_decisions,   3) \
X(a, STATIC,   SINGULAR, BOOL,     include_telemetry,   4) \
X(a, STATIC,   SINGULAR, BOOL,     include_faults,    5) \
X(a, STATIC,   SINGULAR, BOOL,     include_ota,       6) \
X(a, STATIC,   SINGULAR, UINT64,   since_event_id,    7)
#define gate_v1_DashboardSubscription_CALLBACK pb_default_field_callback
#define gate_v1_DashboardSubscription_DEFAULT NULL

#define gate_v1_TimeWindow_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_minute_of_day,   1) \
X(a, STATIC,   SINGULAR, UINT32,   end_minute_of_day,   2) \
X(a, STATIC,   SINGULAR, UINT32,   days_of_week_mask,   3)
#define gate_v1_TimeWindow_CALLBACK NULL
#define gate_v1_TimeWindow_DEFAULT NULL

#define gate_v1_Allowlistentry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   plate_text,        1) \
X(a, CALLBACK, REPEATED, UENUM,    allowed_classes,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  time_windows,      3) \
X(a, CALLBACK, SINGULAR, STRING,   owner_name,        4) \
X(a, CALLBACK, SINGULAR, STRING,   owner_unit,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  valid_from,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  valid_until,       7) \
X(a, CALLBACK, SINGULAR, STRING,   notes,             8) \
X(a, CALLBACK, SINGULAR, STRING,   added_by,          9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  added_ts,         10)
#define gate_v1_Allowlistentry_CALLBACK pb_default_field_callback
#define gate_v1_Allowlistentry_DEFAULT NULL
#define gate_v1_Allowlistentry_time_windows_MSGTYPE gate_v1_TimeWindow
#define gate_v1_Allowlistentry_valid_from_MSGTYPE google_protobuf_Timestamp
#define gate_v1_Allowlistentry_valid_until_MSGTYPE google_protobuf_Timestamp
#define gate_v1_Allowlistentry_added_ts_MSGTYPE google_protobuf_Timestamp

#define gate_v1_UpsertAllowlistRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   site_id,           1) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           2)
#define gate_v1_UpsertAllowlistRequest_CALLBACK pb_default_field_callback
#define gate_v1_UpsertAllowlistRequest_DEFAULT NULL
#define gate_v1_UpsertAllowlistRequest_entries_MSGTYPE gate_v1_Allowlistentry

#define gate_v1_UpsertAllowlistResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   inserted,          1) \
X(a, STATIC,   SINGULAR, UINT32,   updated,           2)
#define gate_v1_UpsertAllowlistResponse_CALLBACK NULL
#define gate_v1_UpsertAllowlistResponse_DEFAULT NULL

#define gate_v1_ListAllowlistRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   site_id,           1) \
X(a, STATIC,   SINGULAR, UINT32,   page_size,         2) \
X(a, CALLBACK, SINGULAR, STRING,   page_token,        3)
#define gate_v1_ListAllowlistRequest_CALLBACK pb_default_field_callback
#define gate_v1_ListAllowlistRequest_DEFAULT NULL

#define gate_v1_ListAllowlistResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           1) \
X(a, CALLBACK, SINGULAR, STRING,   next_page_token,   2)
#define gate_v1_ListAllowlistResponse_CALLBACK pb_default_field_callback
#define gate_v1_ListAllowlistResponse_DEFAULT NULL
#define gate_v1_ListAllowlistResponse_entries_MSGTYPE gate_v1_Allowlistentry

#define gate_v1_DeleteAllowlistRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   site_id,           1) \
X(a, CALLBACK, REPEATED, STRING,   plate_texts,       2)
#define gate_v1_DeleteAllowlistRequest_CALLBACK pb_default_field_callback
#define gate_v1_DeleteAllowlistRequest_DEFAULT NULL

#define gate_v1_ControlEnvelope_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,telemetry,payload.telemetry),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,fault,payload.fault),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command,payload.command),   4)
#define gate_v1_ControlEnvelope_CALLBACK NULL
#define gate_v1_ControlEnvelope_DEFAULT NULL
#define gate_v1_ControlEnvelope_payload_telemetry_MSGTYPE gate_v1_Telemetry
#define gate_v1_ControlEnvelope_payload_ack_MSGTYPE gate_v1_CommandAck
#define gate_v1_ControlEnvelope_payload_fault_MSGTYPE gate_v1_FaultEvent
#define gate_v1_ControlEnvelope_payload_command_MSGTYPE gate_v1_GateCommand

extern const pb_msgdesc_t gate_v1_BoundingBox_msg;
extern const pb_msgdesc_t gate_v1_Point3D_msg;
extern const pb_msgdesc_t gate_v1_BoundingBox3D_msg;
extern const pb_msgdesc_t gate_v1_PlateDetection_msg;
extern const pb_msgdesc_t gate_v1_VehicleDetection_msg;
extern const pb_msgdesc_t gate_v1_DetectionFrame_msg;
extern const pb_msgdesc_t gate_v1_AuthorizeRequest_msg;
extern const pb_msgdesc_t gate_v1_AuthDecision_msg;
extern const pb_msgdesc_t gate_v1_Telemetry_msg;
extern const pb_msgdesc_t gate_v1_GateCommand_msg;
extern const pb_msgdesc_t gate_v1_CommandAck_msg;
extern const pb_msgdesc_t gate_v1_FaultEvent_msg;
extern const pb_msgdesc_t gate_v1_FaultEvent_ContextEntry_msg;
extern const pb_msgdesc_t gate_v1_OtaManifest_msg;
extern const pb_msgdesc_t gate_v1_OtaChunk_msg;
extern const pb_msgdesc_t gate_v1_OtaProgress_msg;
extern const pb_msgdesc_t gate_v1_DashboardEvent_msg;
extern const pb_msgdesc_t gate_v1_DashboardSubscription_msg;
extern const pb_msgdesc_t gate_v1_TimeWindow_msg;
extern const pb_msgdesc_t gate_v1_Allowlistentry_msg;
extern const pb_msgdesc_t gate_v1_UpsertAllowlistRequest_msg;
extern const pb_msgdesc_t gate_v1_UpsertAllowlistResponse_msg;
extern const pb_msgdesc_t gate_v1_ListAllowlistRequest_msg;
extern const pb_msgdesc_t gate_v1_ListAllowlistResponse_msg;
extern const pb_msgdesc_t gate_v1_DeleteAllowlistRequest_msg;
extern const pb_msgdesc_t gate_v1_ControlEnvelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define gate_v1_BoundingBox_fields &gate_v1_BoundingBox_msg
#define gate_v1_Point3D_fields &gate_v1_Point3D_msg
#define gate_v1_BoundingBox3D_fields &gate_v1_BoundingBox3D_msg
#define gate_v1_PlateDetection_fields &gate_v1_PlateDetection_msg
#define gate_v1_VehicleDetection_fields &gate_v1_VehicleDetection_msg
#define gate_v1_DetectionFrame_fields &gate_v1_DetectionFrame_msg
#define gate_v1_AuthorizeRequest_fields &gate_v1_AuthorizeRequest_msg
#define gate_v1_AuthDecision_fields &gate_v1_AuthDecision_msg
#define gate_v1_Telemetry_fields &gate_v1_Telemetry_msg
#define gate_v1_GateCommand_fields &gate_v1_GateCommand_msg
#define gate_v1_CommandAck_fields &gate_v1_CommandAck_msg
#define gate_v1_FaultEvent_fields &gate_v1_FaultEvent_msg
#define gate_v1_FaultEvent_ContextEntry_fields &gate_v1_FaultEvent_ContextEntry_msg
#define gate_v1_OtaManifest_fields &gate_v1_OtaManifest_msg
#define gate_v1_OtaChunk_fields &gate_v1_OtaChunk_msg
#define gate_v1_OtaProgress_fields &gate_v1_OtaProgress_msg
#define gate_v1_DashboardEvent_fields &gate_v1_DashboardEvent_msg
#define gate_v1_DashboardSubscription_fields &gate_v1_DashboardSubscription_msg
#define gate_v1_TimeWindow_fields &gate_v1_TimeWindow_msg
#define gate_v1_Allowlistentry_fields &gate_v1_Allowlistentry_msg
#define gate_v1_UpsertAllowlistRequest_fields &gate_v1_UpsertAllowlistRequest_msg
#define gate_v1_UpsertAllowlistResponse_fields &gate_v1_UpsertAllowlistResponse_msg
#define gate_v1_ListAllowlistRequest_fields &gate_v1_ListAllowlistRequest_msg
#define gate_v1_ListAllowlistResponse_fields &gate_v1_ListAllowlistResponse_msg
#define gate_v1_DeleteAllowlistRequest_fields &gate_v1_DeleteAllowlistRequest_msg
#define gate_v1_ControlEnvelope_fields &gate_v1_ControlEnvelope_msg

/* Maximum encoded size of messages (where known) */
/* gate_v1_PlateDetection_size depends on runtime parameters */
/* gate_v1_DetectionFrame_size depends on runtime parameters */
/* gate_v1_AuthorizeRequest_size depends on runtime parameters */
/* gate_v1_AuthDecision_size depends on runtime parameters */
/* gate_v1_OtaProgress_size depends on runtime parameters */
/* gate_v1_DashboardEvent_size depends on runtime parameters */
/* gate_v1_DashboardSubscription_size depends on runtime parameters */
/* gate_v1_Allowlistentry_size depends on runtime parameters */
/* gate_v1_UpsertAllowlistRequest_size depends on runtime parameters */
/* gate_v1_ListAllowlistRequest_size depends on runtime parameters */
/* gate_v1_ListAllowlistResponse_size depends on runtime parameters */
/* gate_v1_DeleteAllowlistRequest_size depends on runtime parameters */
#define GATE_V1_GATE_SERVICE_PB_H_MAX_SIZE       gate_v1_OtaChunk_size
#define gate_v1_BoundingBox3D_size               37
#define gate_v1_BoundingBox_size                 24
#define gate_v1_CommandAck_size                  192
#define gate_v1_ControlEnvelope_size             537
#define gate_v1_FaultEvent_ContextEntry_size     74
#define gate_v1_FaultEvent_size                  534
#define gate_v1_GateCommand_size                 247
#define gate_v1_OtaChunk_size                    4112
#define gate_v1_OtaManifest_size                 361
#define gate_v1_Point3D_size                     15
#define gate_v1_Telemetry_size                   206
#define gate_v1_TimeWindow_size                  18
#define gate_v1_UpsertAllowlistResponse_size     12
#define gate_v1_VehicleDetection_size            75

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
